### ISSUE TITLE
Generation of possible diordered site 

### ISSUE THREAD

**Issue by Asif-Iqbal-Bhatti** [giprayogo/SHRY#11]
Hallo,

I want to clarify regarding running SHRY program. I am playing around with LiPSCl crystal which is known for site disorder. THere is a orderser structure in Materials Project but that is one of the approximation. From the literature I found the cif for this and try to construct a supercell with CL/S or sometime Li. Below is the output. To have some disorder we need to enlarge a supercell.

''' Run configurations:
----------------------------------------------------------------------------------------
  * SHRY version = 1.1.7
  * structure_file = Li6PS5Cl_structure_from_2012_paper.cif
  * from_species =
  * to_species =
  * scaling_matrix = [1 1 1]
  * symmetrize = False
  * sample = 10
  * symprec = 0.01
  * angle_tolerance = 5.0
  * dir_size = 10000
  * write_symm = False
  * t-kind = sum

----------------------------------------------------------------------------------------
Reading _atom_site_label from Li6PS5Cl_structure_from_2012_paper.cif

Setting Substitutor with Structure
LabeledStructure
Full Formula (X26.88 Li21.12 P4 S52 Cl4.0)
Reduced Formula: X26.88Li21.12P4S52Cl4.0
abc   :   9.850000   9.850000   9.850000
angles:  90.000000  90.000000  90.000000
pbc   :       True       True       True
Sites (108)
  #  SP                        a        b         c  _atom_site_label
---  -----------------  --------  -------  --------  ------------------
  0  X:0.560, Li:0.440   0.3161   0.3161    0.9771   ('Li1', 'X')
  1  X:0.560, Li:0.440   0.6839   0.6839    0.9771   ('Li1', 'X')
  2  X:0.560, Li:0.440   0.6839   0.3161    0.0229   ('Li1', 'X')
  3  X:0.560, Li:0.440   0.3161   0.6839    0.0229   ('Li1', 'X')
  4  X:0.560, Li:0.440   0.9771   0.3161    0.3161   ('Li1', 'X')
  5  X:0.560, Li:0.440   0.9771   0.6839    0.6839   ('Li1', 'X')
  6  X:0.560, Li:0.440   0.0229   0.6839    0.3161   ('Li1', 'X')
  7  X:0.560, Li:0.440   0.0229   0.3161    0.6839   ('Li1', 'X')
  8  X:0.560, Li:0.440   0.3161   0.9771    0.3161   ('Li1', 'X')
  9  X:0.560, Li:0.440   0.6839   0.9771    0.6839   ('Li1', 'X')
 10  X:0.560, Li:0.440   0.3161   0.0229    0.6839   ('Li1', 'X')
 11  X:0.560, Li:0.440   0.6839   0.0229    0.3161   ('Li1', 'X')
 12  X:0.560, Li:0.440   0.3161   0.8161    0.4771   ('Li1', 'X')
 13  X:0.560, Li:0.440   0.6839   0.1839    0.4771   ('Li1', 'X')
 14  X:0.560, Li:0.440   0.6839   0.8161    0.5229   ('Li1', 'X')
 15  X:0.560, Li:0.440   0.3161   0.1839    0.5229   ('Li1', 'X')
 16  X:0.560, Li:0.440   0.9771   0.8161    0.8161   ('Li1', 'X')
 17  X:0.560, Li:0.440   0.9771   0.1839    0.1839   ('Li1', 'X')
 18  X:0.560, Li:0.440   0.0229   0.1839    0.8161   ('Li1', 'X')
 19  X:0.560, Li:0.440   0.0229   0.8161    0.1839   ('Li1', 'X')
 20  X:0.560, Li:0.440   0.3161   0.4771    0.8161   ('Li1', 'X')
 21  X:0.560, Li:0.440   0.6839   0.4771    0.1839   ('Li1', 'X')
 22  X:0.560, Li:0.440   0.3161   0.5229    0.1839   ('Li1', 'X')
 23  X:0.560, Li:0.440   0.6839   0.5229    0.8161   ('Li1', 'X')
 24  X:0.560, Li:0.440   0.8161   0.3161    0.4771   ('Li1', 'X')
 25  X:0.560, Li:0.440   0.1839   0.6839    0.4771   ('Li1', 'X')
 26  X:0.560, Li:0.440   0.1839   0.3161    0.5229   ('Li1', 'X')
 27  X:0.560, Li:0.440   0.8161   0.6839    0.5229   ('Li1', 'X')
 28  X:0.560, Li:0.440   0.4771   0.3161    0.8161   ('Li1', 'X')
 29  X:0.560, Li:0.440   0.4771   0.6839    0.1839   ('Li1', 'X')
 30  X:0.560, Li:0.440   0.5229   0.6839    0.8161   ('Li1', 'X')
 31  X:0.560, Li:0.440   0.5229   0.3161    0.1839   ('Li1', 'X')
 32  X:0.560, Li:0.440   0.8161   0.9771    0.8161   ('Li1', 'X')
 33  X:0.560, Li:0.440   0.1839   0.9771    0.1839   ('Li1', 'X')
 34  X:0.560, Li:0.440   0.8161   0.0229    0.1839   ('Li1', 'X')
 35  X:0.560, Li:0.440   0.1839   0.0229    0.8161   ('Li1', 'X')
 36  X:0.560, Li:0.440   0.8161   0.8161    0.9771   ('Li1', 'X')
 37  X:0.560, Li:0.440   0.1839   0.1839    0.9771   ('Li1', 'X')
 38  X:0.560, Li:0.440   0.1839   0.8161    0.0229   ('Li1', 'X')
 39  X:0.560, Li:0.440   0.8161   0.1839    0.0229   ('Li1', 'X')
 40  X:0.560, Li:0.440   0.4771   0.8161    0.3161   ('Li1', 'X')
 41  X:0.560, Li:0.440   0.4771   0.1839    0.6839   ('Li1', 'X')
 42  X:0.560, Li:0.440   0.5229   0.1839    0.3161   ('Li1', 'X')
 43  X:0.560, Li:0.440   0.5229   0.8161    0.6839   ('Li1', 'X')
 44  X:0.560, Li:0.440   0.8161   0.4771    0.3161   ('Li1', 'X')
 45  X:0.560, Li:0.440   0.1839   0.4771    0.6839   ('Li1', 'X')
 46  X:0.560, Li:0.440   0.8161   0.5229    0.6839   ('Li1', 'X')
 47  X:0.560, Li:0.440   0.1839   0.5229    0.3161   ('Li1', 'X')
 48  P                   0.5      0.5       0.5      ('P',)
 49  P                   0.5      0        -0        ('P',)
 50  P                  -0        0.5      -0        ('P',)
 51  P                   0        0         0.5      ('P',)
 52  S                   0.1211   0.98789   0.6211   ('S3',)
 53  S                   0.8789   0.01211   0.6211   ('S3',)
 54  S                   0.8789   0.98789   0.3789   ('S3',)
 55  S                   0.1211   0.01211   0.3789   ('S3',)
 56  S                   0.6211   0.1211    0.98789  ('S3',)
 57  S                   0.6211   0.8789    0.01211  ('S3',)
 58  S                   0.3789   0.8789    0.98789  ('S3',)
 59  S                   0.3789   0.1211    0.01211  ('S3',)
 60  S                   0.98789  0.6211    0.1211   ('S3',)
 61  S                   0.01211  0.6211    0.8789   ('S3',)
 62  S                   0.98789  0.3789    0.8789   ('S3',)
 63  S                   0.01211  0.3789    0.1211   ('S3',)
 64  S                   0.98789  0.1211    0.6211   ('S3',)
 65  S                   0.01211  0.8789    0.6211   ('S3',)
 66  S                   0.98789  0.8789    0.3789   ('S3',)
 67  S                   0.01211  0.1211    0.3789   ('S3',)
 68  S                   0.1211   0.6211    0.98789  ('S3',)
 69  S                   0.8789   0.6211    0.01211  ('S3',)
 70  S                   0.8789   0.3789    0.98789  ('S3',)
 71  S                   0.1211   0.3789    0.01211  ('S3',)
 72  S                   0.6211   0.98789   0.1211   ('S3',)
 73  S                   0.6211   0.01211   0.8789   ('S3',)
 74  S                   0.3789   0.98789   0.8789   ('S3',)
 75  S                   0.3789   0.01211   0.1211   ('S3',)
 76  S                   0.1211   0.48789   0.1211   ('S3',)
 77  S                   0.8789   0.51211   0.1211   ('S3',)
 78  S                   0.8789   0.48789   0.8789   ('S3',)
 79  S                   0.1211   0.51211   0.8789   ('S3',)
 80  S                   0.6211   0.6211    0.48789  ('S3',)
 81  S                   0.6211   0.3789    0.51211  ('S3',)
 82  S                   0.3789   0.3789    0.48789  ('S3',)
 83  S                   0.3789   0.6211    0.51211  ('S3',)
 84  S                   0.1211   0.1211    0.48789  ('S3',)
 85  S                   0.8789   0.1211    0.51211  ('S3',)
 86  S                   0.8789   0.8789    0.48789  ('S3',)
 87  S                   0.1211   0.8789    0.51211  ('S3',)
 88  S                   0.6211   0.48789   0.6211   ('S3',)
 89  S                   0.6211   0.51211   0.3789   ('S3',)
 90  S                   0.3789   0.48789   0.3789   ('S3',)
 91  S                   0.3789   0.51211   0.6211   ('S3',)
 92  S                   0.48789  0.6211    0.6211   ('S3',)
 93  S                   0.51211  0.6211    0.3789   ('S3',)
 94  S                   0.48789  0.3789    0.3789   ('S3',)
 95  S                   0.51211  0.3789    0.6211   ('S3',)
 96  S                   0.48789  0.1211    0.1211   ('S3',)
 97  S                   0.51211  0.8789    0.1211   ('S3',)
 98  S                   0.48789  0.8789    0.8789   ('S3',)
 99  S                   0.51211  0.1211    0.8789   ('S3',)
100  S:0.630, Cl:0.370   0        0         0        ('Cl1',)
101  S:0.630, Cl:0.370  -0        0.5       0.5      ('Cl1',)
102  S:0.630, Cl:0.370   0.5      0         0.5      ('Cl1',)
103  S:0.630, Cl:0.370   0.5      0.5      -0        ('Cl1',)
104  S:0.370, Cl:0.630   0.75     0.75      0.75     ('Cl2',)
105  S:0.370, Cl:0.630   0.25     0.25      0.75     ('Cl2',)
106  S:0.370, Cl:0.630   0.25     0.75      0.25     ('Cl2',)
107  S:0.370, Cl:0.630   0.75     0.25      0.25     ('Cl2',)
Traceback (most recent call last):
Space group: F -4 2 3 (216)
Total 96 symmetry operations
SymmetrizedStructure
Full Formula (X26.88 Li21.12 P4 S52 Cl4.0)
Reduced Formula: X26.88Li21.12P4S52Cl4.0
abc   :   9.850000   9.850000   9.850000
angles:  90.000000  90.000000  90.000000
Sites (108)
  #  SP                      a        b       c  Wyckoff    _atom_site_label
---  -----------------  ------  -------  ------  ---------  ------------------
  0  X:0.560, Li:0.440  0.3161  0.3161   0.9771  48h        ('Li1', 'X')
  1  P                  0.5     0.5      0.5     4b         ('P',)
  2  S                  0.1211  0.98789  0.6211  48h        ('S3',)
  3  S:0.630, Cl:0.370  0       0        0       4a         ('Cl1',)
  4  S:0.370, Cl:0.630  0.75    0.75     0.75    4d         ('Cl2',)

Processing disorder sites.
  File "/home/asifem/miniconda3/bin/shry", line 8, in <module>
    sys.exit(main())
  File "/home/22/miniconda3/lib/python3.10/site-packages/shry/script.py", line 287, in main
    helper = ScriptHelper(
  File "/home/22/miniconda3/lib/python3.10/site-packages/shry/main.py", line 265, in __init__
    self.substitutor = Substitutor(
  File "/home/22/miniconda3/lib/python3.10/site-packages/shry/core.py", line 454, in __init__
    self.structure = structure
  File "/home/22/miniconda3/lib/python3.10/site-packages/shry/core.py", line 547, in structure
    raise NeedSupercellError(
shry.core.NeedSupercellError: Can't fit Cl37S63 within 4 sites (enlarge by 25.0000x)'''

Li has 0.44 the rest I filled with vacancy using X (label and site label). I could not find example for vacancy X. Is this the right methodology. As the supercell size gets, machine gives memory error. I hope you can clarify how to play around with complex system.

Dank u.
Asif

**Comment by kousuke-nakano** [comment]
Dear @Asif-Iqbal-Bhatti Thank you very much for the question. Since SHRY employs the supercell approach, it assumes that the number of atoms/the total number of sites for each Wyckoff position is an integer. 

> X:0.560, Li:0.440 0.3161 0.3161 0.9771 48h ('Li1', 'X')

For instance, the concentration of Li (at 48h Wyckoff positions) is 0.440 in your compound. So, when you employ 1x1x1 supercell (i.e., scaling_matrix = [1 1 1]), 48 * 0.440 = 21.12 is not an integer. If you want to use 0.440, you should enlarge the supercell such that the ratio is an integer. I recommend that you use (Li:0.5, X:0.5), (S:0.5, Cl:0.5), and (Cl:0.5, S:0.5) for 48h, 4a, and 4d positions with the 1x1x1 supercell, or (Li:0.5, X:0.5), (S:0.666666, Cl:0.333334), and (Cl:0.666666, S:0.333334) for 48h, 4a, 4d positions with the 3x1x1 supercell.

**Comment by kousuke-nakano** [comment]
Dear @Asif-Iqbal-Bhatti, by the way, you can use Discussions for Q&A rather than Issues.

**Comment by Asif-Iqbal-Bhatti** [comment]
THank @kousuke-nakano I will do that in Discussion next time. I will work out the example.

**Comment by kousuke-nakano** [comment]
Dear @Asif-Iqbal-Bhatti, thank you very much. Please feel free to ask us if you need more help!
